version: "3.8"

services:
  whisper:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:11.0.3-devel-ubuntu20.04
        - PYTHON_VERSION=3.9
        - UID=${HOST_UID-1001}
        - GID=${HOST_GID-1001}
      context: ../../
      dockerfile: environments/Dockerfile
    tty: true
    volumes:
        - ../../:/home/challenger/ascender
    ports:
        - 8005:8005